---
apiVersion: enterprise.splunk.com/v2
kind: Standalone
metadata:
  name: standalone-dev-2
  namespace: splunk-dev
  finalizers:
    - enterprise.splunk.com/delete-pvc
  labels:
    app: SplunkStandalone
    type: Splunk
spec:
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.1"
    limits:
      memory: "8Gi"
      cpu: "4"
  etcVolumeStorageConfig:
    storageCapacity: 10Gi
  varVolumeStorageConfig:
    storageCapacity: 100Gi
  defaults: |-
    splunk:
      http_enableSSL: 1
