---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: focalboard-config-v1
  namespace: productivity
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
