# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:TfqEu9fFfgieOGw3oKtFMjV5ujyedmEg2hulDtghd3x/M9bH1wFCJk5Y9i7D/hiOUYWzIMW/s184Q/bMcdNmWIIg9PJGD0qBGE+S4IGvVcJjzeozagPAd9K62BkSiU/WkxE3yjxtjWHdBC4aokovXElGK4wGHG7gMt6ZMWanNhT2FPzUfH4nVYeQRRelUgGjpGlA/BjiL/sbcZAi2E7M9ighlRbY7eh3EuPgyCHpJRaBjpAwT9Mnpw==,iv:SwLUkTap5iD/ehmOtrbmPxTh8oVYa8YvUOEzW+UyFR0=,tag:RWfnupIIm+i5fLk37tD0FA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-24T19:59:21Z"
    mac: ENC[AES256_GCM,data:papLQQF4KBlVCJunMvG1zPrdhvrBKLlMRcP7DWIdlF5KRvQ1YTYej0F7kF6B13M5Bxr5js/BB9s/s1tvnElg1Ac7hpmkRwNKsaKQ/x2DsjernX1x8KaRLHMpop0NL7jZVInqBbQaibMuI+Wn/4AYC7GakOyjtGRDMAA75X9IPio=,iv:e6yyTqWI1B7aOTfrss+cWBar5I9tbqM7uPepb9ulKyI=,tag:Q8iQIWS3Uuw68OxqMPtL8g==,type:str]
    pgp:
        - created_at: "2021-12-24T15:23:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4oVj6E7kUgyAQ//Y9mYvEy2rnAjqA351Nc0HnqBMvhHlyV354E8m9RQK58K
            t6tX5u3+u6hg1RHxaSAam/B7p92vHvPq2ymPi9uCJZqGeioRg5SEDzCZstpEomrR
            T2PCUGU616uLk2b+3v0csERpXENPgbCHE07n933/hbuqpmIwfhIQFCXa+GRI/qbq
            vPEJGCnhuvr8xX9ZNvngw4nbqIAdJqDeLAOgB9CuRk/sW516Oc6K7rd2SGESvjDQ
            gbx8/mrEEnqML2L/k6PSiemcppvMdw4JQoAmYIfqdai7ioo4Hk2klCQfqgUnSbSG
            /O48fHMiJeGY/RFR2o2CTRU1DRrAAyGQtV07TNivqgc0O0vdI3jFVAKBtn4ouzqq
            EWNueaPT+EyQL6vLU9CaOABgpn3kITuimnyt/bDmQOjb2zBv0XIZRgbBJvTP57o0
            +jmW5xpjF/bGf13laG66UPBzRolx3o6fxPHtzC+qdYBTVGiYL/vCurNMWeIUNdzo
            OnvseCoPOgMkbCQhCk4mgk59sjW8EPw2cD2pPgI2W7AJnePuLnHu3czywyUeq/FT
            pflTgkKNzPIOQjeltfZ8uDj8rz3hoOiS6QvmwATkDmFHjPkUZFkWd5Uim3yDbs/x
            xw90xKLjwvZLJSK4HSkCOBf1tTvR9RBNOj8dEcMteihM5DK5sUkDLEaEKAE8aVrS
            XgGH9jcpsPY2K3QJYqz3DRFDiDUQ7YlLZL7qGiAoOdUITVJKn1CcMFlwsherb3d/
            9ae9VotRtyr4XZx1OSOE3KYu8OpCU2GsLzV6ihDBttDF0lG3NRlcC9KN+sl/Jms=
            =0aNF
            -----END PGP MESSAGE-----
          fp: 9B9550919B105F83AE76038D92E332A37D3279E9
        - created_at: "2021-12-24T15:23:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Z1T5Qq18JXAQ//QvVE93TlNH0zlbGJK/YIaW+6NbSaHXas5qkJROqilkS2
            5EmjBmr0kEZ8ZlcFqNZAqUN577q8WcX4t+YWUFpw31Zt3Ai3JmH+6ypWkwqGnrlg
            ewyg6dthn6lrc2ok9IIfQKPuE20hW8HuW6uc53O58/Wl0uaWTScvmJupcamplr04
            Y4SChmTcsGbIfaVeRm2h7NOw18oSdr3+4CQiC6lC07z/yqO6HQ+TnbWmaKMYsRn7
            sSreoaCMhzTzrYDtOjMYFE5afCYZ28qlDNH8Dsq0bjzLXBFmPZZQFUZ9mt4ITkTm
            +PoUtFfDcFq/6POmAXQQ9cVcAKB/Hea4l0YtC7mR6pqDGMFpghhQB8NP87Le2TBf
            RGu2ePNNDhsjLiTnK76cY8Z3/F/c2bV3HREPSOD8VjHI26wdBFuQyz4WI9vGqwsU
            Hraa1SAaJl9HlVXOTFysUcdMUA/L30RHzbJNXrd8kMX2Sf4MHn1WK9+paWWScYTC
            t/DbbL9WmY+m0tuuR5c2tIZGJrNZER/t2/xRlP9W5mml17TOhq57XN/G3yu/6W/t
            PjEWtThjpfcoaAsonG3hQVDMxkMSSXECV2ayAInKrSvRKqeTghaz0eDWtVUAkHT6
            FBk7YEteXseZ7lBzzHImMIVfgfRXHhsOUg6eDo3yR/t2zFBXvsQ+zV4wEXkpSQbS
            XgEYAc8cR5gqTaV76GyJ12Pw+YJZn02b2A6MJMPzW0pP5I5kOFdj24tQR3QympWo
            6FcSv/kQQIrMBrVdn/XteF2ftSiFq+Qu4xdE4XBcKP5XVxfp6+edAR/P8uEborc=
            =LR0b
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
