# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:HIG1Od6k50lJL1NpN6NmaF0EfSQ=,iv:xJX2HAsXomZRjihrw83v+7xZoJjzDthoP0l0W6w/cbg=,tag:pJINNGH0fjrj0lK4GGX3PQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:bWVkczJObX2kV1l7zBaQ0Cp4n7/KaTH/V59Mb1mt5hKCAtruVQ==,iv:B2+owFOffv01kvLhsteiIpgOZzf87sjFD7scNvyYYSU=,tag:XRWw92p2GmSqnoAwjrKAXg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Hi+vEpLn1SDStLBJTS2D,iv:ro2k8UzhSZCKXBqgNnhTJMJRj5LV2+VubFSP781ECuY=,tag:+kWqCpgmaHdvvRS52uR6Zw==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:as1GYlW5pnwKk3dAqjsg6k1iV173Zb3zMRbonaZvH3g=,iv:JUtGy7b2gOETxs+avoa37+qVI7VnVisuj1+HHlMikMk=,tag:Rrw3QQlKz5HIvow5+Zxy8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-30T12:20:36Z"
    mac: ENC[AES256_GCM,data:HvyncU25+iNUmaw8eXpFhB3sN1Ya57pBAnl3fjJ4rcvsUIXSGu+UxPqy0cjfyWgACzyS4SCXR6gD1diXVbAw5Bf/OOluHbl7x/CQ3dSX+Uh3a5aJMPyuilk7lLnmdfjyd/v6ok6N/RKxISiWbda9lQtw+7NfvI67l7a5lvLP/XU=,iv:wHY3eq+qJ/nN9GhMgjcgPaKmFuPj/LnCDrhuGxme7Yw=,tag:MnJlhuG6Ms+jmRKcKehB8w==,type:str]
    pgp:
        - created_at: "2021-11-30T12:20:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4oVj6E7kUgyAQ/+JIy4qZro1FWuMgfFKSaCa+mNUcsCfDv3MBIt+/ZkhKEp
            rPzNpuKeZuFkgmPf1RFSakdfll4z0PnokNl5gfk9yqfXwwDOlhieWaXdwXhO8lre
            bn9cQbqMYO4OgiG07hBlUeka120+78YGZiZDORrw9rHdGlyi1EJ+A4/sjH6Nkuns
            0aWUc/ri7P+9i2HOHzDskTuLMbNKHI+WRd75WujOIFWUF85iMJDYN3ll4MRoU6v6
            xRTDaYgpBFxUL032ZXmi0fEY8OF4v3XOuEiYPO5Zebr715nh0j83uMSekasS+7oD
            fQwyYzR0b2afbqdCh/Ri5PReiqgwDr49/3Ra9JPjdju43uR8ltq3oa+snju/dii2
            o11vpNfuOIkIORMeuqSwPfuCzAL7GTmKqeEaoZLRwB0wgP9NxxBMYFRELg9J2C1j
            Qk3vceO6+QOrbXZKtb5rYez7ww5WzoBSXHrzuOFCHzMWTgVMqdaUhWqphrRhRyzI
            Nc5xqKONNNyEcZzELQebalpuMnW8wcoY4c/GWpsjr3oIg9h1UVB4jPWMS2So9mjT
            8jNwfCIsAP1Uzhoj9Ckhz1DzE3O30HrQwnbda3dqWr0OjFqwI2toFIxi2H4Osrxh
            bdnSCBYZuSekpVpdeSH8IMF7Wr6Ur2ASpzaGEPKBUAG5H28VpZnDckzQKfXG4a3S
            XgFOQ/KTI/vN9Jx2q4Xm9Y8r2Z3hkl2y2oIuIEAPJwAkaXexwbmBl9LKu78325lF
            24oXaNOUGDBQE8eqeu37iVbFydSbbCL5RjV+Z4sVCXkO6dUIJ5oSFz8o9eFvx7U=
            =yXFD
            -----END PGP MESSAGE-----
          fp: 9B9550919B105F83AE76038D92E332A37D3279E9
        - created_at: "2021-11-30T12:20:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Z1T5Qq18JXARAAgY1xDzxEqTnBkrvrpNbaEdGQGvaWaNSzxr/BkoOc03KF
            WF2r84+qzU3JEjyFfsyAmxt4mmIQ6d4yOTNU6pVD4YHe9ThEFAmdNQSQmcYgj3Ev
            Ytbs6OcS4X+xOo8VaRSo+UYJadX8qt7MFCuBPYEboUYnbvdsiOPzRbAR1swZja6P
            tLqB4WzH9PSdkvfBqUf0ZwVQoMdNT3t3O2WxBOnAMQub1eyzidcaXgr6DZOzZeTp
            P36oudgISdI2k9/kSU7gImPgy+OzjuyAcDaM6prX+35mxYSTK8TvcMW3cJ8F2IA3
            2oqYlpVUyRE0g2twbyUVqvzdDeDc8EfkmQEZmNGrgODysFu8MuwHG0weEoPloOQG
            AQPrGOBoCmUz+JvpFmEmCmLuX4MZWN2MVNsGeXBEvWCkv2Mn2CEXZm02fT/zA8VG
            u1WkDcX5XUQiOUIOy+bJuSuANoPJvLIL6OKeQOqQ7vgl0fxbe+iyHvUOatK8aR+D
            29tbZYTrJbJ/m2yZA7cBI2ZVM73t9kHxTVQiWyS0c6fIS32Z69gPNGrco5jPyGIx
            mtLU8rpd93+s7EtJWYtmsgk+Lcpwvyon1fhKw7Miw3FE1B0P4waUW1aYrklf9uYg
            NlpmkHkZxeYOdtzfeGclim2eOAARH+JSLVbM5PmYJ2mza2KnAFO7HFYkcAngrtjS
            XgEfZgIUgzpXV7dqOdLTc1ZECBkUyK75GvLGLwtha7WSiafQJdG9UY1c6hrDz7+K
            avydKbwhkCuCIHvk8GwKV2okKhHwXanerjJIBi1+vf6+aLhi+kG6GgS7PA1YN4I=
            =h7Q7
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
