apiVersion: v1
kind: ConfigMap
metadata:
    name: splunk-licenses
    namespace: splunk-standalone-dev
data:
    enterprise.lic: ENC[AES256_GCM,data:/n39ZSyTL6yxyzAmi0SlmM/G0Npp85jCqXu2CJvsFtW467DyUWCWj+/Ef6uuFB6A0ujFAVBV6/VbU3fhbYoXG/8ztnZUCjxl4TGD/J587guGHJmmy/h+EH9N7zJtOjsTjSLjm/kQGid10KVSCaZELn+MmVe6vvXLLjK8fEfF2+O5Yc3wgrrh3HbUgJlZV2s5kA+DldKF+onHl77ftAMQrr3WM+ai23Jn2hM/0dYdYRcdyMnXlB0c2OML4+e55OY/ulyAAAj5lW3stQDRL1bVfK+BARyFjc68zacHJBcUHXEipCV4591tW9n16uDgB3mRSk41KubpiJBo3wvjH8qhX+1iEstdfmP80alajwPpzVjMV73v2bfpqhImBlq1q/7jKub2BOc5kGCTKsaWvnfEfbW3Wk63c9NNIM20I+o13FegHBf7l46fgnzyZ0uz+rpiQRJquEhI8SfZ6AmLr6TA6MFzjqHIQjLFfdG6chYjILlxmD0UEZHVZpOOV/cq2sEHaxdIinCG2NHjEaIyvcQQatVZ+bw8xRq4LuCm+gCelRvKa/yD5EA9X9SoJlRXxshV9wSXAmbn3O5qHL2/77WG46LiimvKJSdL6UbjhVbQtE2goQaeoUK2RaNwcPPWIuZYsH6WnRHDixYY+qqpRFdpAhmvMwoQILLyz4gp1U9PEuo+kma0WrkeLCMVPZkeqsxWEJrLzXa/Up+Y3L+uBQFsusdLxxFQwK/g8bAuZqTTsGNZaxTZc7QlDg+RNPiphAr6zliDhxXcJXtQvYOj8fSB9HNEwEQP4slwm/xYKAJcS1raO9t6n72oiv5uq4xKt+GxmEQxADGUPjk9KDJvIBSnQUV49y2eY40glhGAFPgTw4uzT+JKD2ki/6sg9oJnwu75KfKNWPJvEbOu97knpPYVXEc/bD0Es4HFXI1aCUn/dZeKQwdHbFT+M09YfTU5ZigoSYmuT36JMY+dFLWqimG5gtSbZhpQ7NwtxJU8XZeiV1mrDXxWZTIKtBVoAdlQqkd0QnY87UEK91/NY3MCVZnuZ1NXklImRhyZYpCwzE9u0Mig+//AdVMsPWWrbFxSbCKxLYBz+1nWRuQah3JfeVlnH+wD8wH3zTiC67IM2e0SpoBGEa/F0DAFsKiReP0mPw9kQsUT+pD/Q2+F91PhUsnlipgDP17BA+/b8qYQsrXZ50Y0BvvOfhUe6q8zgy5L6R1mRB23L8cLF1izu+jBBWiPXg2XCo6QSDvH3iHZtbWphW+tajbWjaqCnyOVA/opuq9EnJPPUnUZGCQgxvqsrGWAe5MsdkugMUZ7GfSPAA4tM3DbQ7r8E/Pv22IumBRbcloBeXI4tUnI3YGcyL5eWNwlQloeFhjDLu3Mi9HPo4PCmuZ2mDqDHvu5Z0jyZnacfP9zMqTpowFs27o3t0BzzVyKcWfS/RMV5eDUMRP+baOA6AD60iQlOrSkgg6CmKSQ2l2gayVJhR24S7mmHhf9Vlxf7kcEeJB6C+cGpiWE8MVGeDTVok/hPZH/VdhGqDhAHpxmJWWfVqL34Hy5wYM2WrnW8pLaYe5LcnLcPvDRkyzvoBbRC0VC7/RoPkfQmGEp+e68BYf6mvJH3VWb1uyQP/V+FGl56NZTKHOcbFflHsS8wZT+E3+YFZI5VKJqBcjF5xowKaxfL77tC39U4+RR6C5Gr90mFUqCDKuZfNwlWqTBdxOlkKNKrgoXPTHeQevXrpLw87p6Dfm24T7+Su/EWa5msXp7U9k1Dn8Kgm+WUXCMFfWVGkB/P+oQ69P0OuctaYcUNRa7wPVuRaog2QzqbqVxRhSo6v0DyLaxqAYs7fCQEuS+ktXEMHj/vifiUYI+UF5btEAPm/H3qOJTNmmrKxIrz0Bpxn5U+n+JrmeH2zYj1bm9WLkBXeyIyQojGhO51t5IXOffM284NPe7tT0xADQBg6uTzZJA7/MNU/bw14sKu953BJKCB78nw1EOgTxc6GsBYfppp5ivSuY9fT2AiRRwaSW0pAPqJQJo,iv:S9UnAmil0ckT/gjEKaW/lA2wa2LHcFg214yrFU5SYNs=,tag:RZckAp+LkKDBjZ5vTBAjOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-22T13:53:34Z"
    mac: ENC[AES256_GCM,data:zNebsXXYvDfGKXAPu27Fy454uC+vzNaA5m9A8wN/TqCN6v3MrNX4HYsgUWup8SOvvQBCmzylOWz+GddcmzRjA1rOb+uHhza9/QN/58z2rf5Aob4rFU8TmZdkHdNF3XOYanwb2kO9Y3rAtgRiTodT57G38FH42Dj0VaVWFx++NQs=,iv:8hV4lgTc7n0BjJro1+jY9UEQm7voGv1g8ZPLrJUSP48=,tag:LVo8JT+DF02zUxGhXW+UdA==,type:str]
    pgp:
        - created_at: "2021-11-22T13:53:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4oVj6E7kUgyAQ//Vz7euRffgitUMq+bfiLg9XBhWHv/CZluvfnxOHUA8GJA
            oHhxyx1nsZiewM2sUo9w7ghpIGtYzKUVhTOC76FephxxEV7H/b5lpklbDmaPnbzb
            3kkWcAL2y6OW+Qy6mAgQXsVKXYaSeKZfwxrWQ4Yf4A01CaOAZLQLAWbtz3TxwS22
            8+sIDV2tVmCsLE3l1fVbSFa0HYJZAXBCkwZVASEIiK6X7omSneE5ZrJr3tbdGkb2
            3asNiVthrGTyAIfiLm1W9L7bVH6rhbDt7TEEWbS3ewlxsnXLiOSrwVWpo8x6m89u
            jxWy6NeMO0kg5hHnTv5w/TBRvnjo7xZnAkSQt14JbDUi87jKr9qBw5sT2vSOhGsR
            LXzQZuEwqojKXKRS28RVUOJLqAD+hyZnhfWHatJsY17s6tfAta35/HZO8uCmgnLT
            DfDhA+fy7H90lfFdvhADalccBVhWKTJrDwxRaFOe4SP9ZzQ4Ej8FW8t5Ro8Mb2hH
            Xzb4+BqV38afS6PSyZnjJZc/SWN6II25lBLsCmlRbwxDMqtY/8ZK7z8EBuLw9AU1
            IJ0h7SQ7gw4OCkqb45dIM1IX3jOstpUemMmx0Jk+l41dPmvCPXPDHYDN2TyO52Bc
            qh/LP0pHgGPfiL2cUThgL06grd0Jc1Q1JAln8s+wpV6BzUNoh+ryg2Q0Yk2uTzTS
            XgFRdcHCKvZ7thiLjx7BqcjScUQUGmjS6pYJzUaihd2j7cxyEgMDStF+l1V1ICXk
            bZJbzefgYpyA/lqqfjlvgU/Z53dPyvwFyrCwSwH27bQGi97Wd/4MtUDsZtKooOA=
            =Q6nD
            -----END PGP MESSAGE-----
          fp: 9B9550919B105F83AE76038D92E332A37D3279E9
        - created_at: "2021-11-22T13:53:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQILA0Z1T5Qq18JXAQ/4ypvH3LHEfqoYvBEUDNB7b0t1tM9rhN7sT+OBBeFImAOM
            QR8whfU480xXrHYAy2498MD0lBNtCBNjeWfnrXaZN639AZs6VqMZmXVii7f6rAJ4
            JtxBe2rDKGAKFZdtBEf0R9voDXGr2NtPs4dzTfoQreRNadStUO45T7OmwQW9Iz7q
            vclkobGLITwrm0fqj6yksbY6lckv8rS84HuM7RinbqO0+YpNfCxCP6jff5BNMkhc
            xAqaOEDSAChmilwvd+22d2WkC6sPoqHhD1tN7Df8ZeSAe61T16OjefFKlDeWrcJP
            2t/vagWP4q/11p3bbI2NPbMVT+slD07jJxD1KNpgP4aowXQPve9SR/N2Rhva+4B3
            QZ74D4aiYphVxDzr9p7t4zSo0m3oCyLaWoTKmUKmUJyd8XQIdsm0/hxMowu4K8Sm
            oP9WVsFykyg+M4vziwyswCe5u8O+CIMrhwCBNTxbxB3bgT8zq2FmLqDubLe/B7k7
            G1lhx2aQV+3t65I2dgrYHggh3dYiF0xhtgX0x5IHeXg7JDMHEkVRaRlTA/hZ45JH
            GsaPEi1vNms4JMkYXXBAuQpjMX3RnJVoxtl5ykNba5LwNzv7YwDk+YiuqQDHivXx
            5y9ga+XDCwYRqx4lAPL30FOSQI06HtKxLRhM7g62TdnB2WEl8dEGjeBnYdDk2tJe
            AcxoERbZBRU6/8y8fiL1yoLheZSY3Ro9WaTr0x5boQuddNGcr89exBH9zXOus67f
            wRmq3m8urEz410Z4iNVdPz+bXQiq6lxxJ9dmsvy/eqnwtq+zIor0IqBPczRrMw==
            =QQXd
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
