---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.10.10.50
        k8s-1:
          ansible_host: 10.10.10.51
        k8s-2:
          ansible_host: 10.10.10.52
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.10.10.53
        k8s-4:
          ansible_host: 10.10.10.54
        k8s-5:
          ansible_host: 10.10.10.55
        k8s-6:
          ansible_host: 10.10.10.56
        k8s-7:
          ansible_host: 10.10.10.57
        k8s-8:
          ansible_host: 10.10.10.58
