---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-config
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
