---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: unpackerr
  namespace: media
spec:
  interval: 5m
  dependsOn:
    - name: longhorn
      namespace: storage
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: unpackerr
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: golift/unpackerr
      tag: 0.9.7
    env:
      TZ: "America/Denver"
    podSecurityContext:
      fsGroup: 0
    persistence:
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume1/data/media/downloads
        mountPath: /downloads
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 750Mi
