kind: Secret
ansible_user: ENC[AES256_GCM,data:v2bCZ127HQ8iiA==,iv:kG37AKFLpkbS14F09vuvD7hT+6XwkAQbDXpt3SeV+yI=,tag:9LHZjWqpNwUNvRSXfveuQA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:A+ik4MfBaSf29KOF,iv:xoZFOZ7a/H1D3wOsUua2Pp3dChByb269hct0iF5UtjA=,tag:8fOQ0oNaMDSC+DZz2pjlpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-24T11:48:13Z"
    mac: ENC[AES256_GCM,data:Zg93ThyDtN4bouK9u6OHAkAVcBQ76ddy/P9AJkkiZJq+R5HfkMpwGioJCDuKyDpuucjaoQkYcLCBMoAeZpyUOtCmMYEhlzOSfaYNIyT2Lp/VlbhAKhoqM7XzbkGkMpZQtnfyxeKi/VKVmJ9E5DVv6T3QiHaiM15utHRgsQQYX9w=,iv:30d/n/gM2W712aJyPaJ+MwPy3h6ipdaamiUoJKCas+I=,tag:F3vmsGUgiUoyFnPAA4xNug==,type:str]
    pgp:
        - created_at: "2021-10-24T11:48:13Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Z1T5Qq18JXARAAkhi3RNQiH6F8nqumNVgw7rIUSEp+4tw8c/54zha32aZt
            L8Oh6lnDG1DP2Xd1DOIwX+QtEYXsVHUjEpBxIPt3dR1/bKNG4c5QZZ9JEdU+xI9A
            KlT3vA+p5FiyH576hBTXRY2kFOIMw/XPqSaYadJtVkngYchQ/DPhLHb/50SKjFYA
            uik8OwEPiKyG2vIGPNrVW6Jb2+tZxQBulvdsjY2WqxN35CD3Xfk7sNwexm1qKoqw
            ORi/QlBYj3bwchXHP3Xz3oESFygW+2abjeVPtCpRddhW5uNbuHpAkTM5ZdVrkfkP
            196LG3MaXGnAl6/Va+b0M6IEsvWj+AazsUD8cEcWQbbLdf5mtuwzvTbqDqB92w6H
            b+pH3LwS/eU6G9tUj3G7udeCXpu24Gxeijn5uSVRrzI8tDSRJpkjmAVxzDAiswsC
            s73GjJjCZNIw4IdpZQuVLBjbyDb3F/BTDy6NVjJRlvJqv9LCeUsI8FdOmhF0cdhS
            dRA0mK2HdTkct9uVe08YNNQAouWKd+rPe8SxeaYltXX02/ORKZM3a4Tjxi9hWXZP
            n2fIgXmGZxlY+0cvTz7dgnIibAh8jisdK/z4cqVpslJPFvGZSUGU2cl7OiVl4D7K
            PCe7tG0RnWVr71joxHkvUBGpUew2XegM6yw4wsAV/Kj7cqp7lJi1rZjTqxoCcwjS
            XgGxOcuwHToGTsUDRPxQMVwvnjZuQT84PXqwGlf92Ff3IFXb7ZgGWGNDNnaEsmF9
            +be9XgxO5Fm5gOLdQ5I2+SbirQNraIb4hyApOWlo/W/jLsRmZS5ndyCG8+NF3l4=
            =vUyk
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    unencrypted_regex: ^(kind)$
    version: 3.7.1
