kind: Secret
ansible_user: ENC[AES256_GCM,data:qSKiOm7wvORVHw==,iv:xaC8tGYZQ1MSe8/WkYR0AW2h2XSSXKkyAtKslqwsC+Q=,tag:+fj9J6gjqwtq1ZWC/6P5iw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:hUA0F/CJlG+3tPmD,iv:iErZZPGw6+oQm6W2582MAgE9GOUrv8nUySVK/7L9oRA=,tag:BQAmR8EwqIg9M4FHPuAq/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-27T13:15:26Z"
    mac: ENC[AES256_GCM,data:uBL4vOde8EYeIckmAjnNoHcCiQtLHWM4QFVVmN5ZxJi3SSK4K+pmgws5bqJgGfHjslwh6gB2lrwEOWOuTYJjVXvL1H5RwBCeI3Vgsam1yKtE3pKzdgkQ9CS+cpUjn//Q5q3jemsNUypheB3CF9lWF32TvuH75L/5dBtRVRMbuUo=,iv:c4faF2KU9DFdsLu8R1yepDg0ckz6C+yHMQqf7GXHWIE=,tag:TzKaY4ZrzD2XrKCrFqTk1Q==,type:str]
    pgp:
        - created_at: "2021-10-27T13:15:26Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Z1T5Qq18JXAQ/+Kw8lueSlAwiiMFelkXEcZ2ADm0yKn5lTyyo/mHR8vvRa
            CUeH7m8Rr2ZT7XoZRB+3Mq4/bvJC1u1afledf8ZQahjege3bhvrEv8NnAMjoi5ky
            htLLBJiOJa4vXVeLLP+hveo5CNjasTXak2aW88GW4sCpUaZoammz3Vz2MZzxrILg
            LDyRmMBuCJ6g8jhQqkr2kojJOnXqG5SDNGGRl6hhY4MMQ4XDFVwQim+PF+rXdKLr
            d4OVtEHp7m5pbjzyU4+SW4XqKV9XTnzrQUd/Jx18bno2iPAA0SnQNwZXm4XHLq8T
            XHCVbXwd7byVIraK9o9ZOn/+LRXBWgDMU6DBpUIjD7M00DMcbHkmpjpGhakssZ+m
            gk2e4diOpHLw4AV8X+2Iip/lOa+nyQWvQdxIaUIxtUCH5P6vt2seJIrCmzl6d2mr
            uKJ519HjiBhlTIRk0lifNUYbWehG5n56vcDhAlOPdwG8xuBZ/yU4Z4ObpvopUkMG
            DD4z78mX6HgmEn/6J5uIROlCtvnKi4ZVf4XiKGnLnfqAGn6Vu1umViN/3mDC6eEG
            0N5Xss8XxGIYruivJsVFLA1pJyD+EFQt6I1z5/CxUEXINh9Z/pXgPw0g597PxkcA
            P1+HV4xY6p4sMNby4Vrr4T4AYXE5A3hb+1lPy9hPQ4DhrkQuJoKo4M7bzboyyaHS
            XAFdQ4QZsUvgj3WcJYMgmWu61hCIVNaMs+ctNrDJd4puqqciIzcOdQYk4lfmL57f
            PbJrUkAEJUNDR4D8AjXtqfE6Nkat9m0ZN3m1hnMuZHeE8EVLgBO01XumoOCk
            =febT
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    unencrypted_regex: ^(kind)$
    version: 3.7.1
