---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-config-v1
  namespace: productivity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-db-v1
  namespace: productivity
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn-retain
