---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prymalinstynct.github.io/helm-charts/
      chart: busybox-chart
      version: 0.1.15
      sourceRef:
        kind: HelmRepository
        name: prymalinstynct-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-provisioner
      namespace: storage
  values:
    image: busybox
    imageTag: latest
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
    # upgrade strategy type (e.g. Recreate or RollingUpdate)
    strategyType: Recreate
