---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio-operator
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://operator.min.io
      chart: minio-operator
      version: 4.3.5
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: flux-system
      interval: 5m
  values:
    operator:
      image:
        repository: minio/operator
        tag: v4.3.5
        pullPolicy: IfNotPresent
      imagePullSecrets: [ ]
      initcontainers: [ ]
      replicaCount: 1
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
      nodeSelector: { }
      affinity: { }
      tolerations: [ ]
      topologySpreadConstraints: [ ]
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
          ephemeral-storage: 500Mi

    console:
      image:
        repository: minio/console
        tag: v0.12.5
        pullPolicy: IfNotPresent
      imagePullSecrets: [ ]
      initcontainers: [ ]
      replicaCount: 1
      nodeSelector: { }
      affinity: { }
      tolerations: [ ]
      topologySpreadConstraints: [ ]
      resources: { }
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      ingress:
        main:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-production"
            hajimari.io/enable: "true"
            hajimari.io/icon: "database"
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "networking-basic-auth@kubernetescrd"
          hosts:
            - host: "minio.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "minio.${SECRET_DOMAIN}"
              secretName: "minio-tls"
