apiVersion: v1
kind: ConfigMap
metadata:
  name: dyndns-updater
  namespace: default
data:
  dyndns-updater.sh:: |
    #!/bin/bash

    curl -X PUT "https://api.cloudflare.com/client/v4/zones/$ZONE_ID/dns_records/$RECORD_ID" \
        -H "Authorization: Bearer $AUTH_KEY" \
        -H "Content-Type: application/json" \
        --data "{\"type\":\"A\",\"name\":\"$NAME\",\"content\":\"`curl ifconfig.co`\"}"
