# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:lTM1hiZS4Ex71FvkwvvdJ8XGroKF/pcmyi5qdMw7B8l1sjakLw==,iv:OgA5zv364UV14s9tUOaByibqknxZygjKrK+M8hHQJ4k=,tag:7ZWenFWkO1e+FzYO1qyaSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-24T12:53:24Z"
    mac: ENC[AES256_GCM,data:/FLb+qCTedksXJiCphTeoPzB6s44mpPnu+qd3lieS6Qw54KoYi+tINq0Y1oERplmrNwyFniH1hPBrJOO7WU5sKuNJ2EPMVUlIyubrD+2Bnv6sGLvDtaIBuDJdcRfruG6u+mdv2xYVoZVD8IPAJd8lt508Z43Wmurb8+aRmJdiMs=,iv:rnKtjlVRPwuMukAhpSFDCS1ncCDeaQ7dWL1LLSPciIM=,tag:wdmrEVdGkdFZT+RMjKTfQQ==,type:str]
    pgp:
        - created_at: "2021-11-24T12:53:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4oVj6E7kUgyAQ//UUIGSuB7LyUsTwgIMHEHIvtB91fCmk7DT5E7OsOiSYRy
            Hc/5asFwzVmYQFUfpgNneI+CR+XAKw2p5qYTjKEunugT4RxIQJqAx0JEPcbwu+ZF
            2Ct2eZoHESH4avpZ3RSghtULiBp/Ix0I/wKNzWqRSbEb6TwyX5n0UZsrD4d5zyrE
            zzq4MfI4tExMHsLWOJ+wE4aRuk1X5+wLn3fM8QkEMbQpMOe6BINTReaQwdr0ZmWz
            w5o4RnoZE7fUoIVfMPG47GnVCaVy9Goh1H9yDwmqDBaWqL0PCSdE9PKeWc0h4lYg
            Tf4ykh4QrAWX1gx3Qhfp14nY9FQCc68lnuz5ztV/TnWC3EseCL8Mb/tBCqSBy5ik
            ZF0DxBHAPM1AQjjKv3Fju66MENxYojMO2fH/+BWowIY471oURfRrHu9quy/47gMY
            mK3HqgFvJbPCwpTZznM+iLAmUJQjYXV0NdXt8RwEBD4Ovsw43SdI1DcdW3bWk+6J
            pNDUwkI22J6TLO2xsyHw53Kh+FNazQ1HIIB5dSCLUsKrCu3eWdO2eSFLewlVRytI
            BDPothyDXz1gPz731I88yAR1BNe+h9aLsQeritFp2UF5jaluH9X2K64oUIl9t0KO
            aSe4si8ep+bjrV/dTJ/wtKWZzLp4Tj/gj1lFFteEhmLQVPerQpH62fqvJpz3f1bS
            XAEazCTjGqQIumwUxQnIymmfUAyJDFOsn5DQMwjmRnSje/NVnIsTYBteywlyfDz9
            cfrUAFhRkYyNLVsecKyrzW6wLDzRtzFIchGPVdSi0Cw1ggoB2Tpv+346bICn
            =H29w
            -----END PGP MESSAGE-----
          fp: 9B9550919B105F83AE76038D92E332A37D3279E9
        - created_at: "2021-11-24T12:53:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0Z1T5Qq18JXAQ/+L1cWsLLk0Mewwe2t87WYRbR4Rd7xVDPXvxgOD6rHBH5I
            2UuRoQoY6SpGZ8B1Wq8h9tV4Jbv8eVRNurHxwUvuVAndj2oVTXGxG9mcavlCE0Eh
            uwLJN8RZLUE/Q9MxK2lk2i62R0gueRHAcfRF6BeStS9VM4raGiZ+/aFfxqwtTwaW
            Gl1VgfwGOBCVYuPz+ROSbnYtjyRgdlSspGWXTEDIWo7wyZ+YkHDAqQ7nz5HnHokV
            ErG+4jLsMZehLCjzZTIQqNgI5l4eLfBTMXG6Nlbn6eHFZAoPzrix0zYnrOJ6xOvB
            fM/J6W2+yPBLYTUxtC57tajvMscs41Tcl4kZqM+qD2E2IzbzEQ8l4N3hrgLB6dkw
            rOysUQSJuX+PfOZIha6/yyr39T4Iq2Iocy9jrWizmGzAYZHafqp7Be5lVNrmvUIN
            x7VhryfsTp12YmatJE2XbsGYugDBOViuRQv2ZCPsbXI8j16HGDoSOVKB1SXEWgrn
            V4IhIOQOW7TTUrecwvexGyoxU0wKmEOSVD6+J0LylX51ADZ2CMMiTy930Mjyj6pj
            ec1Cphsc0Zo6g+ENYaakqF/WdYbeNhfRXQE6nrk9RkT3HOYeN7KTfAabY+baMNoi
            IkR4g1rBhlGZNMUfkeiwsXxpyFF2EmL5aICXjaLivEd4+nOW+C7xLjfTao0ItpvS
            XAHn+BHXKODm11/cIv/LdPyxCCxu6yy35g7PYl7cLbJNaQbuOVmcl8dtWY+Kef+a
            CmcLemUs2sjQQPsnNsJQwloM75AIF+2y+jtEVOv1qofGbUKxlReOkoVkv/v1
            =WH+r
            -----END PGP MESSAGE-----
          fp: ABA7AA0FB42E30E3D6589E083A93AC25EBDFE560
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
